In [1]:
import numpy as np

# Task 1.1: Create 1D NumPy array for cost price
cost_price = np.array([1500, 3000, 5000])

# Task 1.2: Create 2D NumPy array for daily sales
# Rows -> Items (Headphones, Smartwatches, Speakers)
# Columns -> Days (Mon, Tue, Wed, Thu)
daily_sales = np.array([
    [10, 15, 8, 12],   # Headphones
    [5, 7, 4, 6],     # Smartwatches
    [2, 3, 2, 4]      # Speakers
])

# Task 1.3: Print shape and dimensions
print("Cost Price Array:")
print("Shape:", cost_price.shape)
print("Dimensions:", cost_price.ndim)

print("\nDaily Sales Array:")
print("Shape:", daily_sales.shape)
print("Dimensions:", daily_sales.ndim)

Cost Price Array:
Shape: (3,)
Dimensions: 1

Daily Sales Array:
Shape: (3, 4)
Dimensions: 2


In [2]:
import numpy as np

# Sample data
# Rows = products, Columns = days
daily_sales = np.array([
    [10, 12, 9, 11],
    [8, 7, 10, 9],
    [15, 14, 16, 13]
])

# Cost price per product
cost_price = np.array([100, 150, 200])

print("Original Daily Sales:\n", daily_sales)
daily_sales_bonus = daily_sales + 2
print("\nDaily Sales after adding bonus units:\n", daily_sales_bonus)

scaled_sales = np.sqrt(daily_sales_bonus)
print("\nSquare root of sales values:\n", scaled_sales)

Original Daily Sales:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Daily Sales after adding bonus units:
 [[12 14 11 13]
 [10  9 12 11]
 [17 16 18 15]]

Square root of sales values:
 [[3.46410162 3.74165739 3.31662479 3.60555128]
 [3.16227766 3.         3.46410162 3.31662479]
 [4.12310563 4.         4.24264069 3.87298335]]


In [3]:
import numpy as np

sales = np.array([
    [10, 12, 9, 11],    # Headphones
    [8, 7, 10, 9],     # Smartwatches
    [15, 14, 16, 13]   # Speakers
])

print("Sales Data:\n", sales)

smartwatches_sales = sales[1, :]
print("\nSmartwatches sales for all days:\n", smartwatches_sales)

first_two_days = sales[:, 0:2]
print("\nSales for all products (Monday & Tuesday):\n", first_two_days)

speakers_thursday = sales[2][3]
print("\nSpeakers sales on Thursday:\n", speakers_thursday)

sub_array = sales[0:2, 0:2]
print("\n2x2 Sub-array (Headphones & Smartwatches, Mon & Tue):\n", sub_array)

Sales Data:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Smartwatches sales for all days:
 [ 8  7 10  9]

Sales for all products (Monday & Tuesday):
 [[10 12]
 [ 8  7]
 [15 14]]

Speakers sales on Thursday:
 13

2x2 Sub-array (Headphones & Smartwatches, Mon & Tue):
 [[10 12]
 [ 8  7]]


In [4]:
import numpy as np

daily_sales = np.array([
    [10, 12, 9, 11],    # Headphones
    [8, 7, 10, 9],     # Smartwatches
    [15, 14, 16, 13]   # Speakers
])

print("Original 3x4 Daily Sales:\n", daily_sales)

flattened_sales = daily_sales.reshape(12)
print("\nFlattened 1D array:\n", flattened_sales)

reshaped_sales = daily_sales.reshape(2, 6)
print("\nReshaped 2x6 matrix:\n", reshaped_sales)

discount_percentages = np.linspace(0, 100, 10)
print("\nDiscount Percentages:\n", discount_percentages)


Original 3x4 Daily Sales:
 [[10 12  9 11]
 [ 8  7 10  9]
 [15 14 16 13]]

Flattened 1D array:
 [10 12  9 11  8  7 10  9 15 14 16 13]

Reshaped 2x6 matrix:
 [[10 12  9 11  8  7]
 [10  9 15 14 16 13]]

Discount Percentages:
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [5]:
import numpy as np

# Existing sales data (used for Task 5.3)
daily_sales = np.array([
    [10, 12, 9, 11],    # Headphones
    [8, 7, 10, 9],     # Smartwatches
    [15, 14, 16, 13]   # Speakers
])

# Task 5.1
# Generate a 3x4 array of predicted sales (0 to 20)
predicted_sales = np.random.randint(0, 21, size=(3, 4))
print("Predicted Sales (Next Week):\n", predicted_sales)


# Task 5.2
# Generate 5 random numbers between 0 and 1
random_values = np.random.rand(5)
print("\nRandom Values (0 to 1):\n", random_values)

# Task 5.3
# Use np.sum()

# Total items sold over all 4 days
total_items_all_days = np.sum(daily_sales)
print("\nTotal items sold over all 4 days:", total_items_all_days)

# Total items sold for each product (sum across rows)
total_per_product = np.sum(daily_sales, axis=1)
print("\nTotal items sold for each product:", total_per_product)


Predicted Sales (Next Week):
 [[ 1  3  9  4]
 [15  6  6  6]
 [ 8 18  7 13]]

Random Values (0 to 1):
 [0.4614805  0.23296567 0.12318175 0.21774841 0.397471  ]

Total items sold over all 4 days: 134

Total items sold for each product: [42 34 58]
