In [2]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

print(marks)
# ---------- Task A1: Metadata Discovery ----------

# Shape of the array
print("Shape:", marks.shape)

# Total number of elements
print("Total elements:", marks.size)

# Data type of elements
print("Data type:", marks.dtype)


# ---------- Task A2: Data Indexing & Slicing ----------

# All marks for the 2nd student (index 1)
print("2nd student marks:", marks[1])

# All marks for the 3rd subject across all students (index 2)
print("3rd subject marks:", marks[:, 2])

# Specific mark for Student 1 in Subject 2 (row 0, col 1)
print("Student 1, Subject 2 mark:", marks[0, 1])


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
Shape: (5, 3)
Total elements: 15
Data type: int64
2nd student marks: [45 60 55]
3rd subject marks: [90 55 95 35 75]
Student 1, Subject 2 mark: 85


In [3]:
import numpy as np

# Given data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# ---------- Task B1: Means and Averages ----------

# Average marks for each student (row-wise)
student_avg = marks.mean(axis=1)
print("Average marks per student:", student_avg)

# Average marks for each subject (column-wise)
subject_avg = marks.mean(axis=0)
print("Average marks per subject:", subject_avg)


# ---------- Task B2: Filtering Top Performers ----------

# Students whose average marks >= 80
top_students = np.where(student_avg >= 80)[0] + 1  # +1 for student numbering
print("Top performing students (avg >= 80):", top_students)


# ---------- Task B3: Global Adjustments (Broadcasting) ----------

# Add 5 grace marks to every subject for every student
updated_marks = marks + 5
print("Updated marks after grace:\n", updated_marks)

Average marks per student: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Average marks per subject: [61.2 69.4 70. ]
Top performing students (avg >= 80): [1 3]
Updated marks after grace:
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [4]:
import numpy as np

# Given data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# ---------- Task C1: Pass / Fail Mapping ----------

# Pass = 1 if mark >= 50, Fail = 0 if mark < 50
status_matrix = np.where(marks >= 50, 1, 0)
print("Pass / Fail Status Matrix:\n", status_matrix)


# ---------- Task C2: Data Cleaning ----------

# Replace all marks below 40 with 0
cleaned_marks = np.where(marks < 40, 0, marks)
print("Cleaned Marks Matrix:\n", cleaned_marks)

Pass / Fail Status Matrix:
 [[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]
Cleaned Marks Matrix:
 [[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


In [ ]:
import numpy as np

# G
# iven data
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

# Calculate average marks per student
student_avg = marks.mean(axis=1)

# ---------- Task D1: Grade Allocation ----------

# Initialize score array with zeros
grade_score = np.zeros_like(student_avg)

# Apply grading rules
grade_score = np.where(student_avg >= 85, 10,
               np.where(student_avg >= 70, 8,
               np.where(student_avg >= 50, 6, 0)))

print("Student Averages:", student_avg)
print("Grade Scores:", grade_score)


Student Averages: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Grade Scores: [ 8  6 10  0  8]


In [6]:
import numpy as np

# Let's create an original 'marks' array
marks = np.array([[85, 90], [78, 92]])
print("Original marks:\n", marks)

# 1. Create a backup of the marks array (Deep Copy)
backup = marks.copy()

# 2. Modify the original array (Setting first element to 0)
marks[0, 0] = 0

# 3. Check if the backup changed or remained original
print("\nModified marks:\n", marks)
print("Backup array (should be unchanged):\n", backup)

if np.array_equal(marks, backup):
    print("\nResult: The backup changed! (Data integrity compromised)")
else:
    print("\nResult: The backup remained original. (Data integrity maintained)")


Original marks:
 [[85 90]
 [78 92]]

Modified marks:
 [[ 0 90]
 [78 92]]
Backup array (should be unchanged):
 [[85 90]
 [78 92]]

Result: The backup remained original. (Data integrity maintained)
