In [1]:
import numpy as np

# Create electricity array
electricity = np.random.randint(120, 651, size=(4, 7))

print("Electricity Data:\n", electricity)



Electricity Data:
 [[440 320 228 354 283 641 360]
 [594 344 388 295 521 294 411]
 [449 525 592 234 519 594 421]
 [120 374 227 478 587 163 243]]


In [2]:
print("Shape:", electricity.shape)
print("Number of Dimensions:", electricity.ndim)
print("Total Number of Elements:", electricity.size)
print("Data Type:", electricity.dtype)


Shape: (4, 7)
Number of Dimensions: 2
Total Number of Elements: 28
Data Type: int64


In [3]:
# Average electricity per hostel
avg_per_hostel = np.mean(electricity, axis=1)

# Maximum usage per hostel
max_per_hostel = np.max(electricity, axis=1)

# Hostel with highest average usage
highest_avg_hostel = np.argmax(avg_per_hostel)

print("Average per Hostel:", avg_per_hostel)
print("Max per Hostel:", max_per_hostel)
print("Hostel with Highest Average Usage:", highest_avg_hostel)



Average per Hostel: [375.14285714 406.71428571 476.28571429 313.14285714]
Max per Hostel: [641 594 594 587]
Hostel with Highest Average Usage: 2


In [4]:
# Total electricity per day
total_per_day = np.sum(electricity, axis=0)

# Day with highest total consumption
highest_day = np.argmax(total_per_day)

print("Total per Day:", total_per_day)
print("Day with Highest Consumption:", highest_day)

Total per Day: [1603 1563 1435 1361 1910 1692 1435]
Day with Highest Consumption: 4


In [5]:
import numpy as np

# Part A
electricity = np.random.randint(120, 651, size=(4, 7))

print("Electricity Data:\n", electricity)

# Part C
penalized_usage = np.where(electricity > 550,
                           electricity * 1.20,
                           electricity)

print("\nPenalized Usage:\n", penalized_usage)

Electricity Data:
 [[472 222 167 251 203 517 312]
 [453 272 243 225 197 280 294]
 [570 373 335 378 394 556 569]
 [568 354 231 517 567 580 449]]

Penalized Usage:
 [[472.  222.  167.  251.  203.  517.  312. ]
 [453.  272.  243.  225.  197.  280.  294. ]
 [684.  373.  335.  378.  394.  667.2 682.8]
 [681.6 354.  231.  517.  680.4 696.  449. ]]


In [6]:
# Weekly average per hostel
hostel_avg = np.mean(electricity, axis=1).reshape(4, 1)

# Boolean comparison matrix
comparison_matrix = electricity > hostel_avg

print("Hostel Weekly Averages:\n", hostel_avg)
print("\nComparison Matrix (True = Above Avg):\n", comparison_matrix)

Hostel Weekly Averages:
 [[306.28571429]
 [280.57142857]
 [453.57142857]
 [466.57142857]]

Comparison Matrix (True = Above Avg):
 [[ True False False False False  True  True]
 [ True False False False False False  True]
 [ True False False False False  True  True]
 [ True False False  True  True  True False]]


In [7]:
reshaped_1x28 = electricity.reshape(1, 28)

print("Shape:", reshaped_1x28.shape)
print(reshaped_1x28)



Shape: (1, 28)
[[472 222 167 251 203 517 312 453 272 243 225 197 280 294 570 373 335 378
  394 556 569 568 354 231 517 567 580 449]]


In [8]:
reshaped_2x14 = electricity.reshape(2, 14)

print("Shape:", reshaped_2x14.shape)
print(reshaped_2x14)

Shape: (2, 14)
[[472 222 167 251 203 517 312 453 272 243 225 197 280 294]
 [570 373 335 378 394 556 569 568 354 231 517 567 580 449]]


In [1]:
import numpy as np

# =========================
# PART A – ARRAY CREATION
# =========================

# Task A1
electricity = np.random.randint(120, 651, size=(4, 7))

print("Electricity Data:\n", electricity)

# Task A2 – Array Attributes
print("\n--- Array Attributes ---")
print("Shape:", electricity.shape)
print("Dimensions:", electricity.ndim)
print("Total Elements:", electricity.size)

Electricity Data:
 [[243 524 288 483 534 586 177]
 [186 544 613 214 428 328 301]
 [238 505 159 247 151 535 408]
 [320 121 604 349 646 224 462]]

--- Array Attributes ---
Shape: (4, 7)
Dimensions: 2
Total Elements: 28


In [2]:
pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 566.2 kB/s  0:00:17m0:00:0100:01

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
